name: Call Resume Parsing
on:
  push:
    branches: 
      - main 
  pull_request:
    branches:
      - main
      
jobs:
  post-delta-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last 2 commits

      - name: Get previous commit SHA
        id: prev-commit
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            echo "::set-output name=SHA::$(git rev-parse HEAD^1)"
          else
            echo "::set-output name=SHA::$(git rev-parse HEAD)"
          fi

      - name: Get current commit SHA
        id: curr-commit
        run: echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Identify changed files
        id: changed-files
        run: |
          if [ "${{ steps.prev-commit.outputs.SHA }}" != "${{ steps.curr-commit.outputs.SHA }}" ]; then
            git diff --name-only ${{ steps.prev-commit.outputs.SHA }} ${{ steps.curr-commit.outputs.SHA }} > changed_files.txt
          else
            git diff --name-only HEAD > changed_files.txt
          fi
          echo "::set-output name=files::$(cat changed_files.txt)"
          
      - name: Print changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt
          
      - name: Prepare file URLs
        id: prepare-urls
        run: |
          repo="https://raw.githubusercontent.com/${{ github.repository }}/main"
          files=$(cat changed_files.txt)
          urls=()
          for file in $files; do
            url="$repo/$file"
            urls+=("\"$url\"")
          done
          echo "::set-output name=urls::[${urls[*]}]"

      - name: Generate Bearer Token
        id: generate-token
        run: |
          response=$(curl -X POST 'https://coe-asset-b9jxgzf0.authentication.eu10.hana.ondemand.com/oauth/token' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'grant_type=client_credentials&client_id=sb-secure-app!t501469&client_secret=65408566-e1d9-44d8-9beb-c20aee3c0368$vh7rsr9UibThjxFGSbVYI2PiXg4ab8DPLTS-Au4mWm8=')
          token=$(echo $response | jq -r '.access_token')
          echo "::set-output name=token::$token"

      - name: Make POST request
        run: |          
          urls_json=$(echo "${{ steps.prepare-urls.outputs.urls }}" | jq -c .)
          curl -X 'POST' \
          'https://resumescreeningapi-boring-panther-dl.cfapps.eu10-004.hana.ondemand.com/process_resume' \
          -H 'accept: application/json' \
          -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          -H 'Content-Type: application/json' \
          -d "{\"path\":$urls_json}"
