name: Post Delta File Uploads

on:
  push:
    branches:
      - main

jobs:
  post-delta-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch the last 2 commits

      - name: Get previous commit SHA
        id: prev-commit
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            echo "::set-output name=SHA::$(git rev-parse HEAD^1)"
          else
            echo "::set-output name=SHA::$(git rev-parse HEAD)"
          fi

      - name: Get current commit SHA
        id: curr-commit
        run: echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Identify changed files
        id: changed-files
        run: |
          if [ "${{ steps.prev-commit.outputs.SHA }}" != "${{ steps.curr-commit.outputs.SHA }}" ]; then
            git diff --name-only ${{ steps.prev-commit.outputs.SHA }} ${{ steps.curr-commit.outputs.SHA }} > changed_files.txt
          else
            git diff --name-only HEAD > changed_files.txt
          fi
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Prepare file URLs
        id: prepare-urls
        run: |
          files=$(cat changed_files.txt)
          urls=()
          for file in $files; do
            url="https://raw.githubusercontent.com/sreeniRS/docs/main/SAP_ABAP/$(basename $file)"
            urls+=("\"$url\"")
          done
          echo "::set-output name=urls::[${urls[*]}]"

      - name: Make POST request
        run: |
          curl -X 'POST' \
          'http://127.0.0.1:8080/process_resume' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d "{\"path\":${{ steps.prepare-urls.outputs.urls }}}"
