name: Call Resume Parsing

jobs:
  post-delta-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get previous commit SHA
        id: prev-commit
        run: echo "::set-output name=SHA::$(git rev-parse HEAD^1)"

      - name: Get current commit SHA
        id: curr-commit
        run: echo "::set-output name=SHA::$(git rev-parse HEAD)"

      - name: Identify changed files
        id: changed-files
        run: |
          git diff --name-only ${{ steps.prev-commit.outputs.SHA }} ${{ steps.curr-commit.outputs.SHA }} > changed_files.txt
          echo "::set-output name=files::$(cat changed_files.txt)"

      - name: Prepare file URLs
        id: prepare-urls
        run: |
          files=$(cat changed_files.txt)
          urls=()
          for file in $files; do
            url="https://raw.githubusercontent.com/sreeniRS/docs/main/SAP_ABAP/$(basename $file)"
            urls+=("\"$url\"")
          done
          echo "::set-output name=urls::[${urls[*]}]"

      - name: Make POST request
        run: |
          curl -X 'POST' \
          'https://resumescreeningapi-boring-panther-dl.cfapps.eu10-004.hana.ondemand.com/process_resume' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d "{\"path\":${{ steps.prepare-urls.outputs.urls }}}"
